api=../api
tags=../ref/Tags
github=https://github.com/grace-profiles/rest-api
sourcedir=.
sourceRepo=https://github.com/grace-profiles/rest-api/edit/2023.3.x/docs
safe=UNSAFE
title=Grace Profile : REST API
subtitle=A profile for REST API applications
authors=Michael Yan
copyright=Copyright &copy; 2022-2025 Michael Yan and the original authors. The content is licensed under a Creative Commons Attribution 4.0 International (CC BY SA 4.0) license.
